[package]
name = "icc_assembler"
version = "1.0.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
icc = {path = "../icc"}
regex = "1.5"
clap = "2.33.0"